/**
 *  Data file holding content for a new post
 *  The data fields are used to inject content in the related new Markdown post
 *  The post_o object could be generated by a database or created manually
 */

const newPost = require( './newPost' )

const post_o =
{
  id:        `titre`,          // : lowercase-title
  layout:    `post`,           // : post
  plink:     `posts`,          // : posts || tech || site
  tags:      `post`,           // : post  || tech || site
  
  image:     `image-@400.jpg`, // : 1560_carracci_roma_farnese_1600_bacchus
  title:     `title`,          // : Rome 1600
  subtitle:  `subtitle`,       // : Rome 1600
  author:    `A. Dupin`,
  abstract:  `Blabla...`,         // : A short description...
  
  // comment out img_src if no media
  //img_src:      ``,          // : 1581_Zampieri_1628_sgiovanni
  img_alt:      ``,            // : 1581_Zampieri_1628_sgiovanni
  img_title:    ``,            // : San Giovanni
  img_abstract: ``,            // : San Giovanni
  
}
newPost.createPost( post_o )
